name: CI
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  build:
    uses: status-im/nimbus-common-workflow/.github/workflows/common.yml@main
    with:
      nimble-version: b920dad9ed76c6619be3ec0cfbf0dde6f9e39092
      test-command: |
        env NIMLANG=c nimble test
        env NIMLANG=cpp nimble test

        env nimble examples
