name: CI
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  build:
    uses: status-im/nimbus-common-workflow/.github/workflows/common.yml@main
    with:
      nimble-version: 20e76c3061aeacc27a9740ba467c83645ab49f92
      test-command: |
        env NIMLANG=c nimble test -g
        env NIMLANG=cpp nimble test -g

        env nimble examples
