name: Docgen
on:
  push:
    branches:
      - master
      - docs
      - ci_fix_docs
  workflow_dispatch:

jobs:
  build:
    timeout-minutes: 20

    name: 'Generate & upload documentation'
    runs-on: 'ubuntu-latest'
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions-rs/install@v0.1
        with:
          crate: mdbook
          use-tool-cache: true
          version: "0.4.51"
      - uses: actions-rs/install@v0.1
        with:
          crate: mdbook-toc
          use-tool-cache: true
          version: "0.14.2"
      - uses: actions-rs/install@v0.1
        with:
          crate: mdbook-open-on-gh
          use-tool-cache: true
          version: "2.4.3"
      - uses: actions-rs/install@v0.1
        with:
          crate: mdbook-admonish
          use-tool-cache: true
          version: "1.20.0"
      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: '2.2.4'

      - name: Generate doc
        run: |
          nim --version
          nimble --version
          nimble docs || true

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/book
          force_orphan: true
